### ISSUE TITLE
Consolidate with templates from `cluster-lifecycle`

### ISSUE THREAD

**Issue by pcarney8** [redhat-cop/openshift-templates#20]
Need to merge things over from `cluster-lifecycle` over to this repo

**Comment by oybed** [comment]
Please ensure that we do a "move with history". I see at least one template that has been "duplicated" and added at this point, but would like to ensure we keep the history of these.

**Comment by garethahealy** [comment]
@pcarney8 ; any progress on this?

**Comment by garethahealy** [comment]
Closing as old.
