### ISSUE TITLE
Should nexus be moved to container-quickstarts

### ISSUE THREAD

**Issue by tylerauerbeck** [redhat-cop/openshift-templates#33]
Just looking through some of the templates we have and noticed that there are some templates that may fit better in `container-quickstarts` than here in `openshift-templates`. I'm specifically looking at nexus right now, but wanted to see if there were any other opinions on this before working on building this out / cleaning this up.

**Comment by pabrahamsson** [comment]
We discussed this on today's track call and the general consensus was that we should keep application specific templates out of this repository (container-quickstarts probably being a good home). However this can also get a bit tricky to decide what is "too" application specific.
The group called out the following items as possibly being application specific:
* nexus
* prometheus
* pact-broker
* rhsso
* rhpam
* jenkins?
* slack-notification (in jobs folder)

@pcarney8 what are your thoughts here?

**Comment by garethahealy** [comment]
@pabrahamsson ; was anything agreed on this? or still WIP?

**Comment by garethahealy** [comment]
Closing as old.
