### ISSUE TITLE
Update Sonatype Nexus template to use Nexus OpenShift/Kubernetes Plugin

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/openshift-templates#55]
The new [plugin](https://github.com/sonatype-nexus-community/nexus-kubernetes-openshift) allows for declarative configuration of Sonatype Nexus. In order to achieve this (for now) we need to build a new container image which the plugin bundle layered over top of the Nexus container image. This will require a buildconfig template and modification of the deployment template to use the new container image.

**Comment by tylerauerbeck** [comment]
@InfoSec812 We've got an example of this using the helm chart in containers-quickstarts now. Would this still be useful here? Or is it better to point there now?

**Comment by garethahealy** [comment]
@InfoSec812 ; is this still active or can be closed?
