### ISSUE TITLE
Should we differentiate ocp3 vs ocp4 templates?

### ISSUE THREAD

**Issue by tylerauerbeck** [redhat-cop/openshift-templates#58]
As the title says -- should we differentiate between ocp3 and ocp4 templates (i.e. things that may be specific to ocp4 versus things that are generally applicable to both or just ocp3). Is there a structure that would work best? Or is a README the better way to handle this?

Open to any ideas at this point.

cc/ @redhat-cop/day-in-the-life

**Comment by tylerauerbeck** [comment]
Look at #60 as an example of this

**Comment by garethahealy** [comment]
@tylerauerbeck ; since the apiVersions have been updated to v4 specs, is this still valid? or should it be closed?
