### ISSUE TITLE
Add templates to configure cluster-monitoring in OCP 4

### ISSUE THREAD

**Issue by tylerauerbeck** [redhat-cop/openshift-templates#59]
Allow for configuration of persistent or ephemeral cluster-monitoring settings in OCP4 (as well as configuration of metrics retention period)

**Comment by pabrahamsson** [comment]
Should this be closed by #60 , @tylerauerbeck?

**Comment by tylerauerbeck** [comment]
Yepp, just forgot to link the two. Closing this one out.
