### ISSUE TITLE
CatalogSourceConfig used by operatorhub template is deprecated

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/openshift-templates#79]
https://github.com/redhat-cop/openshift-templates/tree/master/operatorhub uses `CatalogSourceConfig` which is now deprecated: 
- https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-deprecated-features

**Comment by tylerauerbeck** [comment]
Closed by #83
