### ISSUE TITLE
Move from DeploymentConfig to Deployment

### ISSUE THREAD

**Issue by AlbertoPimpo** [redhat-cop/openshift-templates#95]
Since DeploymentConfig are on the way to be decommission, it might make sense to move all those template to use normal Deployments instead.

WDYT? Would you accept PR from the community to move on this?

**Comment by garethahealy** [comment]
@AlbertoPimpo if you want to spend time on doing this, happy to review *BUT* a lot of content in this repo is old and has no automated CI to test on PR, which makes it a bit harder to just accept.

are you actively using the content from this repo? and if so, what and how?

**Comment by AlbertoPimpo** [comment]
> are you actively using the content from this repo? and if so, what and how?

@garethahealy I'm using the Jenkins template. Our users can create on our OKD cluster Jenkins instances using the `jenkins-persistent-template` template. I've seen that there is a Helm chart [here](https://github.com/redhat-cop/helm-charts/blob/main/charts/jenkins/templates/deploymentconfig.yaml) but it also uses deploymentconfig. Maybe it's better to update that one?

**Comment by garethahealy** [comment]
>  I've seen that there is a Helm chart [here](https://github.com/redhat-cop/helm-charts/blob/main/charts/jenkins/templates/deploymentconfig.yaml) but it also uses deploymentconfig. Maybe it's better to update that one?

@AlbertoPimpo ; yes, that sounds like a better option.
